#! /bin/sh
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install composer
sudo apt-get install -y git curl wget zip unzip
sudo apt-get install apache2
sudo a2enmod rewrite
sudo systemctl restart apache2
sudo apt-get install mysql-server
mysql_secure_installation
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get install -y php7.2 php7.2-fpm libapache2-mod-php7.2 php7.2-cli php7.2-curl php7.2-mysql php7.2-sqlite3 php7.2-gd php7.2-xml php7.1-mcrypt php7.2-mbstring php7.2-iconv
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
sudo chown -R $USER $HOME/.composer
sudo add-apt-repository ppa:jonathonf/python-3.6
sudo apt update
sudo apt install python3.6
sudo apt install python3.6-dev
sudo apt install python3.6-venv
wget https://bootstrap.pypa.io/get-pip.py
sudo python3.6 get-pip.py
sudo ln -s /usr/bin/python3.6 /usr/local/bin/python3
sudo ln -s /usr/local/bin/pip /usr/local/bin/pip3
sudo pip3.6 install psutil
sudo apt-get update
sudo apt-get upgrade
